### ISSUE TITLE
possible to change visibility setting of column?

### ISSUE THREAD

**Issue by dave1013** [Comanche/datatables-responsive#45]
When using aoColumns to change the visibility of a column to false, the column still appears.  When removing the datatables-responsible callbacks it works fine.  Is there a way to preserve the bVisible setting?  1.10

```
"aoColumns": [ 
        null,
        null,
        null,
        null,
        null,
        null,
        {"bVisible":    false },
        {"bVisible":    false },
        {"bVisible":    false }
    ] ,
```

**Comment by Hernrup** [comment]
This issue seems to still be in place. For what version was it fixed?

**Comment by Comanche** [comment]
It should be working properly.  Do you have an example to illustrate the problem?
